### ISSUE TITLE
License terms

### ISSUE THREAD

**Issue by mokomull** [yrp604/rappel#1]
I'd like to contribute but I would like a clear indication for the license under which a contribution would be accepted.  I didn't see a `COPYING` or `LICENSE` in the repo.

As a teaser: I have a working but currently memory-leaky port of `assemble_intel` to use the LLVM MC assembler instead of shelling out to nasm. It definitely still needs some clean-up, and it'd probably be nice if I figure out how to support _both_ with user choice.

**Comment by yrp604** [comment]
Cool, thanks for your interest!

I've added a 4 clause bsd license to the project. I totally meant to do this earlier and just spaced on it, thanks for reminding me. Hope this is compatible with what you had in mind.

Cheers, and let me know if you run into any other problems.

Thanks,
yrp
