### ISSUE TITLE
Cannot find -ledit

### ISSUE THREAD

**Issue by VoR0220** [yrp604/rappel#17]
I've installed libedit-dev on debian buster and tried following the steps of running `CC=clang make` and get the following error:

```
/usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libedit.so when searching for -ledit
/usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libedit.a when searching for -ledit
/usr/bin/ld: cannot find -ledit
```

what could be causing this?

**Comment by yrp604** [comment]
Did you install the i386 version of libedit-dev by chance?

**Comment by VoR0220** [comment]
I tried but it seems apt-get couldn't find it?

**Comment by VoR0220** [comment]
Whoops. Figured it out. Never had to add a different architecture specific package before so bit noobish. Anyone lost use this: https://askubuntu.com/questions/472808/why-cant-apt-get-install-the-i386-version-of-any-package
