### ISSUE TITLE
Pid 8 got signal 11, not delivering on numerous opcodes

### ISSUE THREAD

**Issue by VoR0220** [yrp604/rappel#25]
I've been using this for an implementation of a vm I've been working on to debug and get proper test results but I'm starting to come into problems particularly with the string operations movs and cmps as well as anything that loops or uses subroutines. Is there a particular way I should be using this to unlock these capabilities or am I screwed?

**Comment by VoR0220** [comment]
Update: I figured this out. Turns out I'm not writing to valid memory. Need to use .showmap to show what valid memory can be written to which seems to only be a space of about 0x21000 on the stack. Probably isn't going to happen but being able to maybe push the bounds of where memory can be written would be a nice feature to add. Closing.

**Comment by yrp604** [comment]
Yeah, the ability to add arbitrary sections/sizes to the initially generated elf based on some command line flags has been on todo list for a while... it’s a good suggestion, I just need to find time to do it.
