### ISSUE TITLE
Add option to optimise number of columns.

### ISSUE THREAD

**Issue by kcubeterm** [yrp604/rappel#29]
Originally reported in https://github.com/termux/termux-packages/issues/6100

> Currently Rappel displays 4 registers per column. On Android termux with visible size font, the last row gets wrapped. Is it possible to display 2 register per column for a better register view on Termux Android screen

**Comment by yrp604** [comment]
The relevant code is very straight forward and lives here for armv7: https://github.com/yrp604/rappel/blob/master/arch/armv7/display_armv7.c#L25-L45 (arm64 is nearly identical). The last argument to that function is the trailer when printing that register. As you should be able to see, it's currently grouped into blocks of four: tab, tab, tab, newline. If you were to split this into blocks of two (tab, newline, tab, newline) you'd get the desired behavior.

I don't think the phone use case is more popular than the desktop 80+ column terminal so I'm unlikely to change it across the board -- if you have any problems patching it please let me know.

**Comment by kcubeterm** [comment]
Thanks for your kind reply.

Happy new year btw 💝
