### ISSUE TITLE
Only show changed registers

### ISSUE THREAD

**Issue by RalphCorderoy** [yrp604/rappel#32]
I think it would be better by default if only registers which had changed value were displayed, and this may be none.  That would save me having to hunt for the ones I expect to change, and also highlight if unexpected ones had altered.

**Comment by yrp604** [comment]
Changed registers should show up in bright red, isn’t this sufficient to figure out what an instruction changed?

**Comment by RalphCorderoy** [comment]
Yes, I agree, though red doesn't make it through into cut-and-paste transcripts of interactions, which is why I didn't know it occurred. Also, all the non-red registers still add clutter, particularly vertically so I can see less of what was entered at a time and have to instead try and remember what has scrolled away.

**Comment by yrp604** [comment]
Please don't file issues without using the software.

I'm not going to implement this, the code that implements register coloring is [here](https://github.com/yrp604/rappel/blob/53237141c07e083606339f21abe894629349cdc1/include/printfmt.h#L8-L14), you can modify it to suit your needs.
