### ISSUE TITLE
execlp: No such file or directory

### ISSUE THREAD

**Issue by RickCarlino** [yrp604/rappel#4]
Ran `sudo apt-get install libedit-dev` followed by `make`.

Then I ran `bin/rappel` on a Linux based x86 system.

Received the following error:

```
> nop
Trying to assemble(4):
nop
nasm is pid 5678
execlp: No such file or directory
nasm exited 1.
Got asm(0):
'' assembled to 0 length bytecode
> 
```

**Comment by yrp604** [comment]
Looks like `nasm` isn't installed. `apt-get install nasm` and give it a shot?

**Comment by RickCarlino** [comment]
D'oh! I read the part about installing `libedit-dev` and somehow missed the next part about `nasm`/`binutils` packages.

Thanks for the quick response!
